[package]
autobins = false
name = "cell-asciidoc"
version = "0.1.0"
edition = "2024"

[lib]
name = "ddc_cell_asciidoc"
crate-type = ["cdylib"]
path = "src/main.rs"

[dependencies]
cell-asciidoc-proto = { path = "../cell-asciidoc-proto" }
dodeca-cell-runtime = { path = "../../crates/dodeca-cell-runtime" }
acdc-parser = "0.9.0"
acdc-converters-html = { git = "https://github.com/nlopes/acdc", rev = "3fa5ff2" }
acdc-converters-core = { git = "https://github.com/nlopes/acdc", rev = "3fa5ff2" }
facet-value.workspace = true
tracing.workspace = true
